# Generated by Django 5.1.3 on 2024-11-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.DecimalField(decimal_places=5, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('Assignet_to', models.CharField(max_length=50)),
                ('due_date', models.DecimalField(decimal_places=4, max_digits=50)),
                ('prio', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('subtasks', models.CharField(max_length=20)),
            ],
        ),
    ]
