# Generated by Django 5.1.3 on 2024-11-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join_Backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='label',
            field=models.CharField(default='No Label', max_length=20),
        ),
    ]
