# Generated by Django 5.1.3 on 2024-11-20 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join_Backend_app', '0003_rename_status_subtask_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='title',
        ),
        migrations.AddField(
            model_name='subtask',
            name='tasks',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='Join_Backend_app.tasks'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('urgent', 'Urgent')], default='low', max_length=20),
        ),
    ]
