# Generated by Django 5.1.3 on 2024-11-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join_Backend_app', '0004_rename_email_profile_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='dueDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('urgent', 'Urgent')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='subtasks',
            field=models.JSONField(),
        ),
    ]
