# Generated by Django 5.1.3 on 2024-11-20 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join_Backend_app', '0004_remove_subtask_title_subtask_tasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='tasks',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='Join_Backend_app.tasks'),
        ),
    ]
