# Generated by Django 5.1.3 on 2024-11-20 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join_Backend_app', '0005_alter_subtask_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='tasks',
        ),
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='Join_Backend_app.tasks'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('urgent', 'Urgent')], max_length=20),
        ),
    ]
