# Generated by Django 5.1.3 on 2024-11-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join_Backend_app', '0005_alter_tasks_duedate_alter_tasks_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TitleDiscription', models.CharField(max_length=40)),
            ],
        ),
    ]
