# Generated by Django 5.1.3 on 2024-11-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join_Backend_app', '0006_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='subtasks',
            field=models.CharField(max_length=80),
        ),
    ]
