# Generated by Django 5.1.3 on 2024-11-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join_Backend_app', '0006_remove_subtask_tasks_alter_subtask_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='title',
            field=models.CharField(default='No Title', max_length=100),
        ),
    ]
