# Generated by Django 5.1.3 on 2024-11-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join_Backend_app', '0007_alter_tasks_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
