# Generated by Django 5.1.3 on 2024-11-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join_Backend_app', '0008_alter_tasks_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='contacts',
        ),
        migrations.AddField(
            model_name='tasks',
            name='contacts',
            field=models.ManyToManyField(related_name='tasks', to='Join_Backend_app.profile'),
        ),
    ]
