# Generated by Django 5.1.3 on 2024-11-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join_Backend_app', '0008_subtask_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='subtasks',
        ),
        migrations.AddField(
            model_name='tasks',
            name='subtasks',
            field=models.ManyToManyField(related_name='tasks', to='Join_Backend_app.subtask'),
        ),
    ]
