# Generated by Django 5.1.3 on 2024-11-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join_Backend_app', '0009_remove_tasks_subtasks_tasks_subtasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='TitleDiscription',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='subtasks',
        ),
        migrations.AddField(
            model_name='subtask',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
