# Generated by Django 5.1.3 on 2024-11-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join_Backend_app', '0011_alter_tasks_category_alter_tasks_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='category',
            field=models.CharField(choices=[('todos', 'Todos'), ('inprogress', 'In Progress'), ('await', 'Awaiting Feedback'), ('done', 'Done')], default='todos', max_length=20),
        ),
    ]
