# Generated by Django 5.1.3 on 2024-12-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join_Backend_app', '0012_alter_tasks_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='label',
            field=models.CharField(choices=[('CSS', 'CSS'), ('JS', 'JS'), ('Testing', 'Testing'), ('User Story', 'User Story'), ('Technical Task', 'Technical Task'), ('HTML', 'HTML')], default='CSS', max_length=20),
        ),
    ]
