# Generated by Django 5.1.3 on 2024-11-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join_Backend_app', '0012_alter_subtask_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(blank=True, default='Default Title', max_length=100, null=True),
        ),
    ]
