# Generated by Django 5.1.3 on 2024-12-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join_Backend_app', '0013_alter_tasks_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('medium', 'Medium'), ('low', 'Low')], default='Urgent', max_length=20),
        ),
    ]
