# Generated by Django 5.1.3 on 2024-11-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join_Backend_app', '0013_alter_subtask_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='done',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='task',
        ),
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
