# Generated by Django 5.1.3 on 2024-11-20 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join_Backend_app', '0014_remove_subtask_done_remove_subtask_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='Join_Backend_app.tasks'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
        ),
    ]
